### ISSUE TITLE
Can you explain.

### ISSUE THREAD

**Issue by JamesAnelay** [Creare/CreareSEO#19]
Hi guys great extension, thanks for open-sourcing it!

It's not an issue as such, but I wondered if one of you guys can give some background as to why product pages should have a suffix and category pages NOT?

Cheers!

![screen shot 2015-05-17 at 15 42 55](https://cloud.githubusercontent.com/assets/7728332/7670815/016f0c12-fcac-11e4-8c33-436f5e7114c0.png)

**Comment by bavington** [comment]
Hey James, thanks for your question. This particular recommendation is a fairly lightweight one. It is essentially designed to give a tiny bit more authority to product landing pages in Google's eyes and also ensure they sit correctly in the site hierarchy.

For example, if you took the following URL:
http://domain.com/samsung-ABC123-television

This is treated by Google as a sub-directory tier page, in the same way as:
http://domain.com/samsung-ABC123-television/index.htm

rather than a root page like this:
http://domain.com/samsung-ABC123-television.htm

Which would be our recommendation for the best possible SEO structure. Although it has to be said, that it looks better without an extension and is much more user friendly. If you check out some of the big Magento EE players like paulsmith.co.uk you'll see a lot of sites with good SEO follow this practice.

Let me know what you think

James

**Comment by JamesAnelay** [comment]
Ok thanks @bavington that it is a "fairly lightweight" reccomendation is what I wanted to hear. I prefer no suffix as it looks better and is easier to type, good to know the reason behind the reccomendation so I can make a educated decision as to whether to follow it or not.

Thanks James,
- James
